import { AppState } from '../types';

export const SEED_DATA: AppState = {
  engagements: {
    'eng-001': {
      id: 'eng-001',
      clientName: 'Zenith Corp',
      fiscalYear: 'FY2025',
      startDate: '2025-04-02',
      endDate: null,
      status: 'At Risk',
      isISA315: false,
      statusIsAuto: false,
      manualStatus: 'At Risk',
      leadAuditor: 'Kofi Asante',
      team: ['Kofi Asante', 'Abena Mensah'],
      controlIds: ['ctrl-001','ctrl-002','ctrl-003','ctrl-004','ctrl-005','ctrl-006'],
      evidenceIds: ['evid-001','evid-002','evid-003','evid-004'],
      findingIds: ['find-001','find-002','find-003'],
      milestoneIds: [],
      notes: 'Client has been cooperative. SDLC area needs immediate attention.',
      createdAt: '2025-04-02T09:00:00Z',
      updatedAt: '2025-05-28T14:30:00Z',
    },
    'eng-002': {
      id: 'eng-002',
      clientName: 'Apex Ltd',
      fiscalYear: 'FY2025',
      startDate: '2025-03-15',
      endDate: null,
      status: 'In Progress',
      isISA315: false,
      statusIsAuto: false,
      manualStatus: 'In Progress',
      leadAuditor: 'Nana Sarpong',
      team: ['Nana Sarpong', 'Kwame Darko'],
      controlIds: ['ctrl-007','ctrl-008','ctrl-009','ctrl-010','ctrl-011','ctrl-012'],
      evidenceIds: ['evid-005','evid-006','evid-007','evid-008'],
      findingIds: ['find-004','find-005'],
      milestoneIds: [],
      notes: 'DR testing area outstanding. Follow up with IT Ops manager.',
      createdAt: '2025-03-15T09:00:00Z',
      updatedAt: '2025-05-27T11:00:00Z',
    },
    'eng-003': {
      id: 'eng-003',
      clientName: 'Meridian Group',
      fiscalYear: 'FY2025',
      startDate: '2025-02-20',
      endDate: null,
      status: 'On Track',
      isISA315: false,
      statusIsAuto: false,
      manualStatus: 'On Track',
      leadAuditor: 'Ama Boateng',
      team: ['Ama Boateng'],
      controlIds: ['ctrl-013','ctrl-014','ctrl-015','ctrl-016','ctrl-017','ctrl-018'],
      evidenceIds: ['evid-009','evid-010','evid-011','evid-012'],
      findingIds: ['find-006'],
      milestoneIds: [],
      notes: 'Near completion. ISA sign-off pending.',
      createdAt: '2025-02-20T09:00:00Z',
      updatedAt: '2025-05-29T08:00:00Z',
    },
    'eng-004': {
      id: 'eng-004',
      clientName: 'Stratum Bank',
      fiscalYear: 'FY2025',
      startDate: '2025-05-01',
      endDate: null,
      status: 'Kickoff',
      isISA315: false,
      statusIsAuto: false,
      manualStatus: 'Kickoff',
      leadAuditor: 'Kofi Asante',
      team: ['Kofi Asante', 'Abena Mensah', 'Kwame Darko'],
      controlIds: ['ctrl-019','ctrl-020'],
      evidenceIds: ['evid-013'],
      findingIds: [],
      milestoneIds: [],
      notes: 'Kickoff meeting completed. Risk assessment in progress.',
      createdAt: '2025-05-01T09:00:00Z',
      updatedAt: '2025-05-20T09:00:00Z',
    },
  },

  controls: {
    // Zenith Corp
    'ctrl-001': { id:'ctrl-001', engagementId:'eng-001', domain:'Access Management', name:'User Provisioning & Deprovisioning', description:'Review process for granting and revoking user access', status:'Tested', testingNotes:'Reviewed 25 samples. Process is documented and followed.', testedBy:'Kofi Asante', testedDate:'2025-05-10', evidenceIds:['evid-001'], findingIds:[] },
    'ctrl-002': { id:'ctrl-002', engagementId:'eng-001', domain:'Access Management', name:'Privileged Access Review', description:'Quarterly review of privileged/admin accounts', status:'Exception', testingNotes:'Review not performed in Q1 2025. Finding raised.', testedBy:'Kofi Asante', testedDate:'2025-05-12', evidenceIds:['evid-001'], findingIds:['find-001'] },
    'ctrl-003': { id:'ctrl-003', engagementId:'eng-001', domain:'Change Management', name:'Change Advisory Board Process', description:'Formal CAB approval for production changes', status:'Tested', testingNotes:'CAB minutes reviewed for Jan–Apr. Process effective.', testedBy:'Abena Mensah', testedDate:'2025-05-14', evidenceIds:['evid-002'], findingIds:[] },
    'ctrl-004': { id:'ctrl-004', engagementId:'eng-001', domain:'Change Management', name:'Emergency Change Procedure', description:'Review of emergency change approval and documentation', status:'In Progress', testingNotes:'Sample selection in progress.', testedBy:'Abena Mensah', testedDate:null, evidenceIds:['evid-002'], findingIds:['find-002'] },
    'ctrl-005': { id:'ctrl-005', engagementId:'eng-001', domain:'IT Operations', name:'Backup & Recovery Monitoring', description:'Daily backup job monitoring and exception reporting', status:'Tested', testingNotes:'Backup logs reviewed. No exceptions noted.', testedBy:'Kofi Asante', testedDate:'2025-05-16', evidenceIds:['evid-003'], findingIds:[] },
    'ctrl-006': { id:'ctrl-006', engagementId:'eng-001', domain:'SDLC', name:'Code Review Gate', description:'Mandatory peer code review before merging to main', status:'Exception', testingNotes:'3 hotfix merges bypassed code review. Finding raised.', testedBy:'Abena Mensah', testedDate:'2025-05-18', evidenceIds:['evid-004'], findingIds:['find-003'] },

    // Apex Ltd
    'ctrl-007': { id:'ctrl-007', engagementId:'eng-002', domain:'Access Management', name:'User Provisioning & Deprovisioning', description:'Review process for granting and revoking user access', status:'Tested', testingNotes:'30 samples reviewed. No issues.', testedBy:'Nana Sarpong', testedDate:'2025-04-28', evidenceIds:['evid-005'], findingIds:[] },
    'ctrl-008': { id:'ctrl-008', engagementId:'eng-002', domain:'Access Management', name:'Privileged Access Review', description:'Quarterly review of privileged/admin accounts', status:'Tested', testingNotes:'Q1 review completed and documented.', testedBy:'Nana Sarpong', testedDate:'2025-04-30', evidenceIds:['evid-005'], findingIds:[] },
    'ctrl-009': { id:'ctrl-009', engagementId:'eng-002', domain:'Change Management', name:'Change Advisory Board Process', description:'Formal CAB approval for production changes', status:'Tested', testingNotes:'Effective. CAB minutes and approvals on file.', testedBy:'Kwame Darko', testedDate:'2025-05-02', evidenceIds:['evid-006'], findingIds:[] },
    'ctrl-010': { id:'ctrl-010', engagementId:'eng-002', domain:'IT Operations', name:'Backup & Recovery Monitoring', description:'Daily backup job monitoring and exception reporting', status:'Tested', testingNotes:'Logs reviewed. Automated alerts configured.', testedBy:'Nana Sarpong', testedDate:'2025-05-06', evidenceIds:['evid-007'], findingIds:[] },
    'ctrl-011': { id:'ctrl-011', engagementId:'eng-002', domain:'IT Operations', name:'Disaster Recovery Test', description:'Annual DR test with documented results', status:'Exception', testingNotes:'No DR test conducted in past 12 months. Finding raised.', testedBy:'Nana Sarpong', testedDate:'2025-05-08', evidenceIds:['evid-008'], findingIds:['find-004'] },
    'ctrl-012': { id:'ctrl-012', engagementId:'eng-002', domain:'SDLC', name:'Security Testing Gate', description:'Mandatory security scan before production deployment', status:'Exception', testingNotes:'3 releases skipped security gate. Finding raised.', testedBy:'Kwame Darko', testedDate:'2025-05-10', evidenceIds:[], findingIds:['find-005'] },

    // Meridian Group
    'ctrl-013': { id:'ctrl-013', engagementId:'eng-003', domain:'Access Management', name:'User Provisioning & Deprovisioning', description:'Review process for granting and revoking user access', status:'Tested', testingNotes:'Effective. 20 samples reviewed.', testedBy:'Ama Boateng', testedDate:'2025-03-10', evidenceIds:['evid-009'], findingIds:[] },
    'ctrl-014': { id:'ctrl-014', engagementId:'eng-003', domain:'Access Management', name:'Privileged Access Review', description:'Quarterly review of privileged/admin accounts', status:'Tested', testingNotes:'Q1 review documented and signed off.', testedBy:'Ama Boateng', testedDate:'2025-03-12', evidenceIds:['evid-009'], findingIds:[] },
    'ctrl-015': { id:'ctrl-015', engagementId:'eng-003', domain:'Change Management', name:'Change Advisory Board Process', description:'Formal CAB approval for production changes', status:'Tested', testingNotes:'Strong process. All changes approved through CAB.', testedBy:'Ama Boateng', testedDate:'2025-03-14', evidenceIds:['evid-010'], findingIds:[] },
    'ctrl-016': { id:'ctrl-016', engagementId:'eng-003', domain:'Change Management', name:'Emergency Change Procedure', description:'Review of emergency change approval and documentation', status:'Tested', testingNotes:'2 emergency changes reviewed. Properly documented.', testedBy:'Ama Boateng', testedDate:'2025-03-16', evidenceIds:['evid-010'], findingIds:[] },
    'ctrl-017': { id:'ctrl-017', engagementId:'eng-003', domain:'IT Operations', name:'Backup & Recovery Monitoring', description:'Daily backup job monitoring and exception reporting', status:'Tested', testingNotes:'Effective monitoring in place. No gaps.', testedBy:'Ama Boateng', testedDate:'2025-03-18', evidenceIds:['evid-011'], findingIds:['find-006'] },
    'ctrl-018': { id:'ctrl-018', engagementId:'eng-003', domain:'SDLC', name:'Code Review Gate', description:'Mandatory peer code review before merging to main', status:'Not Started', testingNotes:'', testedBy:'', testedDate:null, evidenceIds:[], findingIds:[] },

    // Stratum Bank
    'ctrl-019': { id:'ctrl-019', engagementId:'eng-004', domain:'Access Management', name:'User Provisioning & Deprovisioning', description:'Review process for granting and revoking user access', status:'In Progress', testingNotes:'Sample selection underway.', testedBy:'Kofi Asante', testedDate:null, evidenceIds:[], findingIds:[] },
    'ctrl-020': { id:'ctrl-020', engagementId:'eng-004', domain:'Change Management', name:'Change Advisory Board Process', description:'Formal CAB approval for production changes', status:'Not Started', testingNotes:'', testedBy:'', testedDate:null, evidenceIds:['evid-013'], findingIds:[] },
  },

  evidence: {
    'evid-001': { id:'evid-001', engagementId:'eng-001', controlId:'ctrl-001', name:'User Access Listing Q1', description:'Full user access report exported from IAM system', status:'Received', requestedDate:'2025-05-05', receivedDate:'2025-05-10', fileUri:null, fileName:null, uploadedBy:'Kofi Asante', notes:'' },
    'evid-002': { id:'evid-002', engagementId:'eng-001', controlId:'ctrl-003', name:'Change Log Export Apr–May', description:'CAB meeting minutes and approved change tickets', status:'Received', requestedDate:'2025-05-08', receivedDate:'2025-05-14', fileUri:null, fileName:null, uploadedBy:'Abena Mensah', notes:'' },
    'evid-003': { id:'evid-003', engagementId:'eng-001', controlId:'ctrl-005', name:'Backup Job Report', description:'Automated backup monitoring report', status:'Requested', requestedDate:'2025-05-20', receivedDate:null, fileUri:null, fileName:null, uploadedBy:'Kofi Asante', notes:'Follow up on May 25' },
    'evid-004': { id:'evid-004', engagementId:'eng-001', controlId:'ctrl-006', name:'DR Test Documentation', description:'Disaster recovery test plan and results', status:'Outstanding', requestedDate:null, receivedDate:null, fileUri:null, fileName:null, uploadedBy:'', notes:'' },
    'evid-005': { id:'evid-005', engagementId:'eng-002', controlId:'ctrl-007', name:'User Access Listing Q1', description:'Full user access report from IAM', status:'Received', requestedDate:'2025-04-20', receivedDate:'2025-04-28', fileUri:null, fileName:null, uploadedBy:'Nana Sarpong', notes:'' },
    'evid-006': { id:'evid-006', engagementId:'eng-002', controlId:'ctrl-009', name:'Change Log Export', description:'CAB meeting minutes Jan–Apr', status:'Received', requestedDate:'2025-04-25', receivedDate:'2025-05-02', fileUri:null, fileName:null, uploadedBy:'Kwame Darko', notes:'' },
    'evid-007': { id:'evid-007', engagementId:'eng-002', controlId:'ctrl-010', name:'Backup Monitoring Report', description:'Monthly backup reports Q1', status:'Received', requestedDate:'2025-04-28', receivedDate:'2025-05-06', fileUri:null, fileName:null, uploadedBy:'Nana Sarpong', notes:'' },
    'evid-008': { id:'evid-008', engagementId:'eng-002', controlId:'ctrl-011', name:'DR Test Plan', description:'Annual disaster recovery test plan and sign-off', status:'Outstanding', requestedDate:'2025-05-08', receivedDate:null, fileUri:null, fileName:null, uploadedBy:'', notes:'Client says test was never conducted' },
    'evid-009': { id:'evid-009', engagementId:'eng-003', controlId:'ctrl-013', name:'User Access Listing', description:'Full IAM user access report', status:'Reviewed', requestedDate:'2025-03-05', receivedDate:'2025-03-10', fileUri:null, fileName:null, uploadedBy:'Ama Boateng', notes:'' },
    'evid-010': { id:'evid-010', engagementId:'eng-003', controlId:'ctrl-015', name:'Change Log Export', description:'CAB minutes Jan–Mar', status:'Reviewed', requestedDate:'2025-03-08', receivedDate:'2025-03-14', fileUri:null, fileName:null, uploadedBy:'Ama Boateng', notes:'' },
    'evid-011': { id:'evid-011', engagementId:'eng-003', controlId:'ctrl-017', name:'Backup Monitoring Report', description:'Q4 and Q1 backup reports', status:'Reviewed', requestedDate:'2025-03-12', receivedDate:'2025-03-18', fileUri:null, fileName:null, uploadedBy:'Ama Boateng', notes:'' },
    'evid-012': { id:'evid-012', engagementId:'eng-003', controlId:null, name:'ISA Sign-off Form', description:'Completed ISA documentation sign-off', status:'Requested', requestedDate:'2025-05-20', receivedDate:null, fileUri:null, fileName:null, uploadedBy:'Ama Boateng', notes:'Pending partner review' },
    'evid-013': { id:'evid-013', engagementId:'eng-004', controlId:'ctrl-020', name:'Kickoff Meeting Agenda', description:'Kickoff meeting agenda and attendee list', status:'Received', requestedDate:'2025-05-01', receivedDate:'2025-05-01', fileUri:null, fileName:null, uploadedBy:'Kofi Asante', notes:'' },
  },

  findings: {
    'find-001': { id:'find-001', engagementId:'eng-001', controlId:'ctrl-002', title:'Privileged access review not performed quarterly', description:'Management has not completed the required quarterly review of privileged and admin accounts. The last review on record was performed in Q3 2024.', severity:'High', domain:'Access Management', owner:'Kofi Asante', managementResponse:'IT management acknowledges the gap. Quarterly reviews have been scheduled going forward.', targetRemediationDate:'2025-07-01', status:'Open', isaReference:'ISA-ZEN-001' },
    'find-002': { id:'find-002', engagementId:'eng-001', controlId:'ctrl-004', title:'Emergency change tickets lack dual approval for production deployments', description:'Review of 12 emergency change tickets identified 4 instances where changes were deployed to production without the required secondary approval.', severity:'Medium', domain:'Change Management', owner:'Abena Mensah', managementResponse:'Process updated. A secondary approver is now mandatory in the ticketing system.', targetRemediationDate:'2025-06-15', status:'In Remediation', isaReference:'ISA-ZEN-002' },
    'find-003': { id:'find-003', engagementId:'eng-001', controlId:'ctrl-006', title:'SDLC code review gate bypassed on hotfix branch', description:'Three production hotfix deployments bypassed the mandatory peer code review process. No compensating control was applied.', severity:'High', domain:'SDLC', owner:'Abena Mensah', managementResponse:'Branch protection rules enforced. Hotfix branch now requires review.', targetRemediationDate:'2025-06-30', status:'Open', isaReference:'ISA-ZEN-003' },
    'find-004': { id:'find-004', engagementId:'eng-002', controlId:'ctrl-011', title:'No formal disaster recovery test conducted in past 12 months', description:'The organisation has not performed a documented DR test in over 12 months, contrary to its IT policy requiring annual testing.', severity:'High', domain:'IT Operations', owner:'Nana Sarpong', managementResponse:'DR test scheduled for Q3 2025.', targetRemediationDate:'2025-09-30', status:'Open', isaReference:'ISA-APX-001' },
    'find-005': { id:'find-005', engagementId:'eng-002', controlId:'ctrl-012', title:'Security testing gate skipped for 3 releases in Q1', description:'Three software releases in Q1 were deployed to production without the mandatory SAST/DAST security scan, creating unmitigated vulnerability exposure.', severity:'Medium', domain:'SDLC', owner:'Kwame Darko', managementResponse:'Pipeline updated. Security gate is now enforced and cannot be bypassed.', targetRemediationDate:'2025-06-01', status:'In Remediation', isaReference:'ISA-APX-002' },
    'find-006': { id:'find-006', engagementId:'eng-003', controlId:'ctrl-017', title:'Job scheduling alerts misconfigured — low severity', description:'Two batch job failure alerts were routing to an inactive email distribution list. Issue was self-reported by the client during testing.', severity:'Low', domain:'IT Operations', owner:'Ama Boateng', managementResponse:'Alert routing corrected. Confirmed by IT Ops.', targetRemediationDate:'2025-04-30', status:'Closed', isaReference:'ISA-MER-001' },
  },

  milestones: {},
};